name: Deploy to Github Pages
on: 
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@master
       
     - name: Deploy
       if: success()
       uses: jeoy/github-deploy-actions@v1.0.1
       env:
         BUILD_DIR: docs/
         ACCESS_TOKEN: ${{secrets.ACTIONS_DEPLOY_KEY}}
         BUILD_SCRIPT: npm ci && npm run build:docs
         FOLDER: docs
