name: Deploy to Github Pages
on: 
  push:
    branches:
      - master
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@master
       
     - name: Build
       run: npm ci && npm run-script build::docs
       
     - name: Deploy
       if: success()
       uses: crazy-max/ghaction-github-pages@master
       with:
          target_branch: gh-pages
          build_dir: docs
       env:
        GITHUB_PAT: ${{secrets.ACTIONS_DEPLOY_KEY}}
