name: Deploy to Github Pages
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@master
       
     - name: Deploy
       uses: JamesIves/github-pages-deploy-action@master
       env:
        ACCESS_TOKEN: ${{secrets.ACTIONS_DEPLOY_KEY}}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: docs
        BUILD_SCRIPT: npm ci && npm run-script build:docs
